global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'example-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']