name: Gateway CI

on:
  push:
    paths:
      - 'infra/api-gateway/**'
  pull_request:
    paths:
      - 'infra/api-gateway/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Gateway
        run: |
          cd infra/api-gateway
          mvn clean verify
